FROM python:3.9-slim

WORKDIR /app

# Установка зависимостей
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копирование исходного кода
COPY src/ .

# Добавим небольшую задержку перед стартом
CMD ["sh", "-c", "sleep 10 && python api_service.py"]